################ English language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 2

################ Tagalog language ##################
[tl]
languageName = "Tagalog"
languageCode = "tl"
contentDir = "content/tagalog"
weight = 1
