############# Tagalog navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Articles"
url = "/blog"
weight = 3

[[main]]
name = "FAQ"
url = "/faq"
weight = 4

[[main]]
name = "More"
url = "/more"
weight = 5


[[main]]
parent = "More"
name = "Comics"
url = "/comics"


[[main]]
parent = "More"
name = "Videos"
url = "/videos"


# [[main]]

# [[main]]
# name = "Elements"
# url = "/elements"


# [[main]]
# weight = 4
# name = "Pages"



# [[main]]
# name = "Contact"
# url = "/contact"

#[[main]]
#parent = "Pages"
#name = "Authors"
#url = "/authors"

# [[main]]
# name = "Mga Aral"
# url = "/categories"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

# [[footer]]
# name = "Elements"
# url = "/elements"
# weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
